#!/bin/bash

# Run a FLExBridge application using the FieldWorks version of mono

scriptdir=$(dirname "$0")
prefix=$(cd "$scriptdir/../.."; /bin/pwd)
lib=$prefix/lib/flexbridge
fwlib=$prefix/lib/fieldworks
MONO_PREFIX=${MONO_PREFIX:-/opt/mono4-sil}

# Allow running ChorusHub as a mono service

if [[ "$1" = "--service" ]]
then
	shift
	SERVICE=true
fi

# Environment settings for running with FieldWorks mono

ARCH=$(uname -m)
[ -z "$BUILD" ] && BUILD=Debug

LD_LIBRARY_PATH="${MONO_PREFIX}/lib:${LD_LIBRARY_PATH}"
GDK_SHARP=/usr/lib/cli/gdk-sharp-2.0/

MONO_RUNTIME=v4.0.30319
MONO_PATH="${GDK_SHARP}:$MONO_PATH"
MONO_DEBUG=explicit-null-checks
MONO_ENV_OPTIONS="-0=-gshared"

# Are we running as installed from a package, or on a development machine?
case "$scriptdir" in
    /usr/*) RUNMODE=INSTALLED ;;
    *) RUNMODE= ;;
esac

(cd $scriptdir && . ./environ-xulrunner)

if [ "$RUNMODE" = "INSTALLED" ]; then
	BASE=$fwlib
else
	BASE=${HOME}/fwrepo/fw
fi

if [[ -d "$BASE" ]]; then
	echo >&2 flexbridge run-app: Warning: Assuming non-existent base "$BASE"
fi

# Add packaged mono items to paths

PKG_CONFIG_PATH="${MONO_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
PATH="${MONO_PREFIX}/bin:${PATH}"
LD_LIBRARY_PATH="${MONO_PREFIX}/lib:${LD_LIBRARY_PATH}"
MONO_GAC_PREFIX="${MONO_PREFIX}:/usr"

if [ "$RUNMODE" = "INSTALLED" ]
then
	COMPONENTS_MAP_PATH="${BASE}"
	FW_ROOT="${BASE}/../../share/fieldworks"
	FW_ROOTDATA="${HOME}/.config/fieldworks"
	FW_ROOTCODE="${BASE}/../../share/fieldworks"
	ICU_DATA="${HOME}/.config/fieldworks/Icu54"
	PATH="${BASE}/icu-bin:${PATH}"
	LD_LIBRARY_PATH="${BASE}:${LD_LIBRARY_PATH}"
	MONO_REGISTRY_PATH="${HOME}/.config/fieldworks/registry"
else
	COMPONENTS_MAP_PATH="${BASE}/Output_${ARCH}/${BUILD}"
	FW_ROOT="${BASE}/DistFiles"
	FW_ROOTDATA="${BASE}/DistFiles"
	FW_ROOTCODE="${BASE}/DistFiles"
	ICU_DATA="${BASE}/DistFiles/Icu54"
	MONO_REGISTRY_PATH="${BASE}/Output_${ARCH}/registry"
	FW_CommonAppData=${BASE}/Output_${ARCH}/VarLibFieldworks
	[ ! -d $FW_CommonAppData ] && mkdir -p $FW_CommonAppData
	MONO_PATH="${BASE}/DistFiles:${BASE}/Output_${ARCH}/${BUILD}:$MONO_PATH"
fi

MONO_TRACE_LISTENER="Console.Out"
#MONO_IOMAP=case
MONO_MWF_SCALING=disable
# if debugging Fieldworks for performance unset DEBUG_ENABLE_PTR_VALIDATION env var.
#DEBUG_ENABLE_PTR_VALIDATION=1

export \
	PATH LD_LIBRARY_PATH PKG_CONFIG_PATH LD_PRELOAD \
	COMPONENTS_MAP_PATH \
	FW_ROOT FW_ROOTCODE FW_ROOTDATA \
	ICU_DATA \
	MONO_PATH MONO_REGISTRY_PATH \
	MONO_RUNTIME MONO_PREFIX \
	MONO_TRACE_LISTENER MONO_IOMAP MONO_MWF_SCALING FW_CommonAppData

#DEBUG_ENABLE_PTR_VALIDATION

#sets keyboard input method to none
unset XMODIFIERS

COMMAND=mono
[[ -n $SERVICE ]] && COMMAND=mono-service

exec $COMMAND --debug "$lib"/"$@"
