version: '{build}'
branches:
  only:
  - develop
image: Visual Studio 2019
init:
  - cmd: |
      set GITVERSION_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
      if defined APPVEYOR_PULL_REQUEST_NUMBER set GitVersion_NoNormalizeEnabled=true
      if defined APPVEYOR_PULL_REQUEST_NUMBER set IGNORE_NORMALISATION_GIT_HEAD_MOVE=1
install:
  - choco install gitversion.portable -pre -y
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
  - pwsh: |
        if ($APPVEYOR_PULL_REQUEST_NUMBER)
        {
          git checkout -b PR-$APPVEYOR_PULL_REQUEST_NUMBER
          gitversion /l console /output buildserver /nonormalize
        }
        else
        {
            gitversion /l console /output buildserver
        }
  - cmd: |
        msbuild l10n\l10n.proj /t:restore
        msbuild l10n\l10n.proj /t:CopyL10nsToDistFiles
build:
  project: build/FLExBridge.proj
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: normal
test: off
artifacts:
- path: output/*nupkg
  name: nuget
deploy:
- provider: Environment
  name: sil-lsdev nuget
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
