#!/bin/bash

# Launch FlexBridge

set -e -o pipefail

# On a developer machine, MONO_ENVIRON may be set, and to the location of the
# FieldWorks environ. Running mono would then re-source the FieldWorks
# environ, and prioritize the FW Geckofx path in LD_LIBRARY_PATH. Prevent this.
unset MONO_ENVIRON

scriptdir="$(dirname "$0")"
prefix=$(cd "$scriptdir/../.."; /bin/pwd)

cd "${scriptdir}"
. environ

(
	XDG_DATA_HOME=${XDG_DATA_HOME:-${HOME}/.local/share}
	FB_SHARE="${XDG_DATA_HOME}/SIL/FlexBridge"

	# Keep localizations files updated.
	# Initialize on fresh install
	if [ ! -f "${FB_SHARE}" ]; then
		mkdir -p "${FB_SHARE}"
	fi
	
	# update new localizations
	if [ "${prefix}" == "/usr" ];then
		cp -a "/var/lib/flexbridge/localizations" "${FB_SHARE}"
	else
		# For developer build. This is still not working correctly.
		cp -a "${prefix}/DistFiles/localizations" "${FB_SHARE}"
	fi
)

cd - >/dev/null
mono "${scriptdir}"/FLExBridge.exe "$@"
