#!/bin/bash
#
# Copyright (c) 2016-2021 SIL International. MIT License.
#
# Launch FLExBridge
# Since FLEx Bridge should always be launched from FieldWorks,
# there is no need to source a new environ file;
# the environment variables should already be set correctly.

set -ueo pipefail

# set HGRCPATH so that we ignore ~/.hgrc files which might have content that is
# incompatible with our version of Mercurial
export HGRCPATH=

if [[ ${CHORUSDEBUGGING-} == "true" ]]; then
  # Note: Change to suspend=y to pause until a debugger attaches.
  FB_MONO_ARGS="${FB_MONO_ARGS-} --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:55502,suspend=n"
fi
script_dir="$(dirname "$0")"
prefix=$(cd "${script_dir}/../.."; /bin/pwd)

cd "${script_dir}"

# Keep localizations files updated.
FB_SHARE="${XDG_DATA_HOME}/SIL/FlexBridge"
mkdir -p "${FB_SHARE}"

if [[ "${prefix}" == "/usr" || -n "${FLATPAK_ID-}" ]]; then
  cp -a "${prefix}/share/flexbridge/localizations" "${FB_SHARE}"
else
  # For developer build. This is still not working correctly.
  cp -a "${prefix}/../DistFiles/localizations" "${FB_SHARE}"
fi

cd - >/dev/null
mono --debug ${FB_MONO_ARGS-} "${script_dir}"/FLExBridge.exe "$@"
