//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEx_ChorusPlugin.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLEx_ChorusPlugin.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Icon chorus {
			get {
				object obj = ResourceManager.GetObject("chorus", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select a Chorus-enabled FieldWorks project to open:.
		/// </summary>
		internal static string kChorusEnabledFwProject {
			get {
				return ResourceManager.GetString("kChorusEnabledFwProject", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot clone onto an existing directory ({0}).
		/// </summary>
		internal static string kCloneTrouble {
			get {
				return ResourceManager.GetString("kCloneTrouble", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to }.
		/// </summary>
		internal static string kCloseCurlyBrace {
			get {
				return ResourceManager.GetString("kCloseCurlyBrace", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to FieldWorks Bridge.
		/// </summary>
		internal static string kFieldWorksBridge {
			get {
				return ResourceManager.GetString("kFieldWorksBridge", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to FieldWorks Project File (*.fwdata)|*.fwdata.
		/// </summary>
		internal static string kFwDataFileFilter {
			get {
				return ResourceManager.GetString("kFwDataFileFilter", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Entry.
		/// </summary>
		internal static string kLexEntryClassLabel {
			get {
				return ResourceManager.GetString("kLexEntryClassLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Locate FieldWorks XML Data File.
		/// </summary>
		internal static string kLocateFwDataFile {
			get {
				return ResourceManager.GetString("kLocateFwDataFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lock file present.
		/// </summary>
		internal static string kLockFilePresent {
			get {
				return ResourceManager.GetString("kLockFilePresent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to It appears that FLEx is running, since the file: {0}.fwdata.lock is present. You need to close FLEx or delete that file, if FLEx is not running, and try again..
		/// </summary>
		internal static string kLockFilePresentMsg {
			get {
				return ResourceManager.GetString("kLockFilePresentMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {&quot;modelversion&quot;: .
		/// </summary>
		internal static string kModelVersion {
			get {
				return ResourceManager.GetString("kModelVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No paths given.
		/// </summary>
		internal static string kNoPathsGiven {
			get {
				return ResourceManager.GetString("kNoPathsGiven", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Not a FieldWorks XML file..
		/// </summary>
		internal static string kNotAnFwXmlFile {
			get {
				return ResourceManager.GetString("kNotAnFwXmlFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &apos;ownerguid&apos; may not be an empty string.
		/// </summary>
		internal static string kOwnerGuidEmpty {
			get {
				return ResourceManager.GetString("kOwnerGuidEmpty", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Item.
		/// </summary>
		internal static string kPossibilityItemLabel {
			get {
				return ResourceManager.GetString("kPossibilityItemLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to List.
		/// </summary>
		internal static string kPossibilityListClassLabel {
			get {
				return ResourceManager.GetString("kPossibilityListClassLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the new folder where the shared data goes..
		/// </summary>
		internal static string kSelectClonedDataFolder {
			get {
				return ResourceManager.GetString("kSelectClonedDataFolder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the folder of the project that you want to obtain..
		/// </summary>
		internal static string ksFindProjectDirectory {
			get {
				return ResourceManager.GetString("ksFindProjectDirectory", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No file path provided. This is a program error..
		/// </summary>
		internal static string ksNoFilePath {
			get {
				return ResourceManager.GetString("ksNoFilePath", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Path Problem.
		/// </summary>
		internal static string ksPathProblem {
			get {
				return ResourceManager.GetString("ksPathProblem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You can not obtain a project that you already have..
		/// </summary>
		internal static string ksTargetDirectoryExistsContent {
			get {
				return ResourceManager.GetString("ksTargetDirectoryExistsContent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Project folder already exists.
		/// </summary>
		internal static string ksTargetDirectoryExistsTitle {
			get {
				return ResourceManager.GetString("ksTargetDirectoryExistsTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Text.
		/// </summary>
		internal static string kTextClassLabel {
			get {
				return ResourceManager.GetString("kTextClassLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Wordform.
		/// </summary>
		internal static string kWfiWordFormClassLabel {
			get {
				return ResourceManager.GetString("kWfiWordFormClassLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Receive project.
		/// </summary>
		internal static string ObtainProjectController_ObtainProjectController_Receive_project {
			get {
				return ResourceManager.GetString("ObtainProjectController_ObtainProjectController_Receive_project", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Receive project.
		/// </summary>
		internal static string ObtainProjectView_DialogTitle {
			get {
				return ResourceManager.GetString("ObtainProjectView_DialogTitle", resourceCulture);
			}
		}
	}
}
