//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.LiftBridge.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.LiftBridge.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Export LIFT Lexicon.
		/// </summary>
		public static string kExportLiftLexicon {
			get {
				return ResourceManager.GetString("kExportLiftLexicon", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Fixing relation links between imported entries.
		/// </summary>
		public static string kFixingRelationLinks {
			get {
				return ResourceManager.GetString("kFixingRelationLinks", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Import LIFT Lexicon.
		/// </summary>
		public static string kImportLiftlexicon {
			get {
				return ResourceManager.GetString("kImportLiftlexicon", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to WeSay Collaboration.
		/// </summary>
		public static string kLabel {
			get {
				return ResourceManager.GetString("kLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to LiftBridge Processing.
		/// </summary>
		public static string kLiftBridgeProcessing {
			get {
				return ResourceManager.GetString("kLiftBridgeProcessing", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Migrating from LIFT version {0} to version {1}.
		/// </summary>
		public static string kLiftVersionMigration {
			get {
				return ResourceManager.GetString("kLiftVersionMigration", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Loading various lists for lookup during import.
		/// </summary>
		public static string kLoadingListInfo {
			get {
				return ResourceManager.GetString("kLoadingListInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Something went wrong while FieldWorks was attempting to import {0}..
		/// </summary>
		public static string kProblem {
			get {
				return ResourceManager.GetString("kProblem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Something went wrong trying to import {0} while merging...
		/// </summary>
		public static string kProblemImportWhileMerging {
			get {
				return ResourceManager.GetString("kProblemImportWhileMerging", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Problem Merging.
		/// </summary>
		public static string kProblemMerging {
			get {
				return ResourceManager.GetString("kProblemMerging", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This operation cannot be undone..
		/// </summary>
		public static string kRedoDescription {
			get {
				return ResourceManager.GetString("kRedoDescription", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Chorus Send/Receive.
		/// </summary>
		public static string kSendReceive {
			get {
				return ResourceManager.GetString("kSendReceive", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Exporting {0} entries from the lexicon.
		/// </summary>
		public static string ksExportingEntries {
			get {
				return ResourceManager.GetString("ksExportingEntries", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This utility allows for exporting Flex lexical data in the LIFT format that WeSay uses, send it to WeSay users, and receive entries from WeSay users..
		/// </summary>
		public static string kWhatDescription {
			get {
				return ResourceManager.GetString("kWhatDescription", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to When you want to share lexical entries with WeSay..
		/// </summary>
		public static string kWhenDescription {
			get {
				return ResourceManager.GetString("kWhenDescription", resourceCulture);
			}
		}
	}
}
