//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLEx_ChorusPluginTests.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class TestResources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal TestResources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLEx_ChorusPluginTests.Properties.TestResources", typeof(TestResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;classdata /&gt;.
		/// </summary>
		internal static string kClassDataEmptyTag {
			get {
				return ResourceManager.GetString("kClassDataEmptyTag", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to TestRepository Cloned: {0}.
		/// </summary>
		internal static string kTestRepoCloned {
			get {
				return ResourceManager.GetString("kTestRepoCloned", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to TestRepository Created: {0}.
		/// </summary>
		internal static string kTestRepoCreated {
			get {
				return ResourceManager.GetString("kTestRepoCreated", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to TestRepository deleted {0}.
		/// </summary>
		internal static string kTestRepoDeleted {
			get {
				return ResourceManager.GetString("kTestRepoDeleted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to TestRepository not deleted in {0}.
		/// </summary>
		internal static string kTestRepoNotDeleted {
			get {
				return ResourceManager.GetString("kTestRepoNotDeleted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;.
		/// </summary>
		internal static string kXmlHeading {
			get {
				return ResourceManager.GetString("kXmlHeading", resourceCulture);
			}
		}
	}
}
