.\"                                      Hey, EMACS: -*- nroff -*-
.TH FLEXBRIDGE 1 "July 12, 2013"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
flexbridge \- program used by fieldworks for collaboration
.SH SYNOPSIS
.B flexbridge
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B flexbridge
command.
.PP
\fBflexbridge\fP is a program that allows remote collaboration among
\fBfieldworks\fP users.  It uses a DVCS system to achieve this purpose,
with communication either over a network (including the Internet) or by
carrying a USB memory device from place to place.
.SH OPTIONS
This program does not follow the usual GNU command line syntax,
with long options starting with two dashes (`-').  All of its options
start with a single dash (`-') regardless of their length.
A summary of options is not included below, because they are too
complex.  \fBflexbridge\fP is not designed to be run from the command line.
It is intended only to be run by the \fBfieldworks\fP program.
.SH SEE ALSO
.BR fieldworks (1).
.SH AUTHOR
\fBflexbridge\fP was written by Randy Regnier <randy_regnier@sil.org>.
.PP
This manual page was written by Stephen McConnel <stephen_mcconnel@sil.org>
to meet the Debian packaging standards.
