<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <Mercurial4ChorusDestDir>$(MSBuildProjectDirectory)</Mercurial4ChorusDestDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LfMergeBridge\LfMergeBridge.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="SIL.Chorus.LibChorus" Version="$(ChorusVersion)" />
    <PackageReference Include="SIL.Chorus.Mercurial" Version="6.*" />
  </ItemGroup>

    <ItemGroup>
      <Content Include="Mercurial\**" CopyToOutputDirectory="Always" />
      <Content Include="MercurialExtensions\**" CopyToOutputDirectory="Always" />
    </ItemGroup>

</Project>