// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LibFLExBridgeChorusPlugin.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LibFLExBridgeChorusPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ksNoFilePath {
            get {
                return ResourceManager.GetString("ksNoFilePath", resourceCulture);
            }
        }
        
        internal static string kScrSectionMultiChapter {
            get {
                return ResourceManager.GetString("kScrSectionMultiChapter", resourceCulture);
            }
        }
        
        internal static string kFwDataFileFilter {
            get {
                return ResourceManager.GetString("kFwDataFileFilter", resourceCulture);
            }
        }
        
        internal static string ksFindProjectDirectory {
            get {
                return ResourceManager.GetString("ksFindProjectDirectory", resourceCulture);
            }
        }
        
        internal static string kRnGenericRecLabel {
            get {
                return ResourceManager.GetString("kRnGenericRecLabel", resourceCulture);
            }
        }
        
        internal static string ObtainProjectController_ObtainProjectController_Receive_project {
            get {
                return ResourceManager.GetString("ObtainProjectController_ObtainProjectController_Receive_project", resourceCulture);
            }
        }
        
        internal static string kUnTitled {
            get {
                return ResourceManager.GetString("kUnTitled", resourceCulture);
            }
        }
        
        internal static string kScrSectionOneChapter {
            get {
                return ResourceManager.GetString("kScrSectionOneChapter", resourceCulture);
            }
        }
        
        internal static string kTextClassLabel {
            get {
                return ResourceManager.GetString("kTextClassLabel", resourceCulture);
            }
        }
        
        internal static string kOwnerGuidEmpty {
            get {
                return ResourceManager.GetString("kOwnerGuidEmpty", resourceCulture);
            }
        }
        
        internal static string kSelectClonedDataFolder {
            get {
                return ResourceManager.GetString("kSelectClonedDataFolder", resourceCulture);
            }
        }
        
        internal static string kScrSectionClassLabel {
            get {
                return ResourceManager.GetString("kScrSectionClassLabel", resourceCulture);
            }
        }
        
        internal static string kCloneTrouble {
            get {
                return ResourceManager.GetString("kCloneTrouble", resourceCulture);
            }
        }
        
        internal static string ObtainProjectView_DialogTitle {
            get {
                return ResourceManager.GetString("ObtainProjectView_DialogTitle", resourceCulture);
            }
        }
        
        internal static string kPossibilityItemLabel {
            get {
                return ResourceManager.GetString("kPossibilityItemLabel", resourceCulture);
            }
        }
        
        internal static string kLexEntryClassLabel {
            get {
                return ResourceManager.GetString("kLexEntryClassLabel", resourceCulture);
            }
        }
        
        internal static string kFBTheTurtle {
            get {
                return ResourceManager.GetString("kFBTheTurtle", resourceCulture);
            }
        }
        
        internal static string kCanonicalBookNumberOutOfRange {
            get {
                return ResourceManager.GetString("kCanonicalBookNumberOutOfRange", resourceCulture);
            }
        }
        
        internal static string kLockFilePresent {
            get {
                return ResourceManager.GetString("kLockFilePresent", resourceCulture);
            }
        }
        
        internal static string kNoPathsGiven {
            get {
                return ResourceManager.GetString("kNoPathsGiven", resourceCulture);
            }
        }
        
        internal static string kFlexNotFound {
            get {
                return ResourceManager.GetString("kFlexNotFound", resourceCulture);
            }
        }
        
        internal static string kScrBookClassLabel {
            get {
                return ResourceManager.GetString("kScrBookClassLabel", resourceCulture);
            }
        }
        
        internal static string kPossibilityListClassLabel {
            get {
                return ResourceManager.GetString("kPossibilityListClassLabel", resourceCulture);
            }
        }
        
        internal static string kStyleLabel {
            get {
                return ResourceManager.GetString("kStyleLabel", resourceCulture);
            }
        }
        
        internal static string kNotAnFwXmlFile {
            get {
                return ResourceManager.GetString("kNotAnFwXmlFile", resourceCulture);
            }
        }
        
        internal static string ksEnvironment {
            get {
                return ResourceManager.GetString("ksEnvironment", resourceCulture);
            }
        }
        
        internal static string kCustomFieldLabel {
            get {
                return ResourceManager.GetString("kCustomFieldLabel", resourceCulture);
            }
        }
        
        internal static string kWfiWordFormClassLabel {
            get {
                return ResourceManager.GetString("kWfiWordFormClassLabel", resourceCulture);
            }
        }
        
        internal static string kLockFilePresentMsg {
            get {
                return ResourceManager.GetString("kLockFilePresentMsg", resourceCulture);
            }
        }
        
        internal static string ksOtherRevisionWarning {
            get {
                return ResourceManager.GetString("ksOtherRevisionWarning", resourceCulture);
            }
        }
        
        internal static string kModelVersion {
            get {
                return ResourceManager.GetString("kModelVersion", resourceCulture);
            }
        }
        
        internal static string ksDiscourseChart {
            get {
                return ResourceManager.GetString("ksDiscourseChart", resourceCulture);
            }
        }
        
        internal static string kChorusEnabledFwProject {
            get {
                return ResourceManager.GetString("kChorusEnabledFwProject", resourceCulture);
            }
        }
        
        internal static string kReversalEntryClassLabel {
            get {
                return ResourceManager.GetString("kReversalEntryClassLabel", resourceCulture);
            }
        }
        
        internal static string kFlexBridge {
            get {
                return ResourceManager.GetString("kFlexBridge", resourceCulture);
            }
        }
        
        internal static string kLocateFwDataFile {
            get {
                return ResourceManager.GetString("kLocateFwDataFile", resourceCulture);
            }
        }
        
        internal static string SendReceiveView_DialogTitleFlexProject {
            get {
                return ResourceManager.GetString("SendReceiveView_DialogTitleFlexProject", resourceCulture);
            }
        }
        
        internal static string kUnidentifiedLabel {
            get {
                return ResourceManager.GetString("kUnidentifiedLabel", resourceCulture);
            }
        }
        
        internal static string ksPathProblem {
            get {
                return ResourceManager.GetString("ksPathProblem", resourceCulture);
            }
        }
        
        internal static string kCloseCurlyBrace {
            get {
                return ResourceManager.GetString("kCloseCurlyBrace", resourceCulture);
            }
        }
    }
}
